# https://geoffboeing.com/share/osmnx-paper.pdf
# https://geoffboeing.com/2016/11/osmnx-python-street-networks/

import os
import re
import stat
import subprocess
from enum import Enum
from os import PathLike
from pathlib import Path
from typing import List, Optional, TypedDict

import shapely
from geopandas import GeoDataFrame

from common.us_census.tiger.utils import (
    get_buffered_region_gdf,
    get_geography_region_name,
    get_region_boundary_gdf,
)

this_dir = os.path.dirname(os.path.abspath(__file__))

OSMOSIS = os.path.join(this_dir, "../../lib/osmosis/latest/bin/osmosis")

DEFAULT_OSM_EXTRACT_BUFFER_DIST_MI = 10
DEFAULT_OSM_EXTRACTS_DIR = Path(
    os.path.abspath(  #
        os.path.join(  #
            os.path.dirname(__file__),  #
            "../../data/processed/osm",
        )
    )
)

# https://wiki.openstreetmap.org/wiki/Key:highway
OSM_MAJOR_ROADWAY_HIGHWAY_TAGS = [
    "motorway",
    "motorway_link",
    "motorway_junction",
    "trunk",
    "trunk_link",
    "primary",
    "primary_link",
    "secondary",
    "secondary_link",
    "tertiary",
    "tertiary_link",
]

# NOTE: Excluding "service" roads.
OSM_MINOR_ROADWAY_HIGHWAY_TAGS = ["residential", "living_street", "unclassified"]

OSM_NONSERVICE_ROADWAY_HIGHWAY_TAGS = (
    OSM_MAJOR_ROADWAY_HIGHWAY_TAGS + OSM_MINOR_ROADWAY_HIGHWAY_TAGS
)


class OSMWaysFilter(Enum):
    """
    Defines filters for OSM ways based on their highway tags.

    Attributes:
        ALL (str): Includes all highway types.
        MAJOR (str): Includes only major highway types (motorway, trunk, primary, secondary, tertiary, and their links).
        MINOR (str): Includes only minor highway types (residential, living_street, unclassified).
        NONSERVICE (str): Includes both major and minor highway types, excluding service roads.
    """

    ALL = "ALL"
    MAJOR = "MAJOR"
    MINOR = "MINOR"
    NONSERVICE = "NONSERVICE"
    ALL_EXCEPT_PARKING_AISLES = "ALL_EXCEPT_PARKING_AISLES"


class OsmFilterConfig(TypedDict):
    name: str
    tag_filters: List[str]


osmosis_tag_filters = {
    OSMWaysFilter.ALL: OsmFilterConfig(
        name="all",
        tag_filters=[
            "--tag-filter",
            "accept-ways",
            "highway=*",
        ],
    ),
    OSMWaysFilter.MAJOR: OsmFilterConfig(
        name="major",
        tag_filters=[
            "--tag-filter",
            "accept-ways",
            f"highway={','.join(OSM_MAJOR_ROADWAY_HIGHWAY_TAGS)}",
        ],
    ),
    OSMWaysFilter.MINOR: OsmFilterConfig(
        name="minor",
        tag_filters=[
            "--tag-filter",
            "accept-ways",
            f"highway={','.join(OSM_MINOR_ROADWAY_HIGHWAY_TAGS)}",
        ],
    ),
    OSMWaysFilter.NONSERVICE: OsmFilterConfig(
        name="nonservice",
        tag_filters=[
            "--tag-filter",
            "accept-ways",
            f"highway={','.join(OSM_NONSERVICE_ROADWAY_HIGHWAY_TAGS)}",
        ],
    ),
    OSMWaysFilter.ALL_EXCEPT_PARKING_AISLES: OsmFilterConfig(
        name="all-except-parking-aisles",
        tag_filters=[
            "--tag-filter",
            "accept-ways",
            "highway=*",
            "reject-ways",
            "service=parking_aisle",
        ],
    ),
}


def get_osm_version_from_pbf_filename(osm_pbf: PathLike):
    osm_version_re = re.compile(r"[^0-9](?P<osm_version>\d{6})\.osm\.pbf$")

    s = str(osm_pbf)

    try:
        match = re.search(osm_version_re, s)

        osm_version = match.group("osm_version")

        return osm_version
    except Exception:
        raise ValueError(f"Invalid OSM PBF filename: {s}")


# Generated by ChatGPT
def output_osmosis_filter_poly(
    region_gdf: GeoDataFrame,  #
    out_filename: str,
) -> str:
    """
    Generates an Osmosis/Polygon Filter File (.poly) from a GeoDataFrame.
    Supports complex geometries, including those with holes.
    SEE: https://wiki.openstreetmap.org/wiki/Osmosis/Polygon_Filter_File_Format

    The .poly file format generated is:

        polygon_name
        <ring_id>
            lon lat
            lon lat
            ...
        END
        <ring_id>
            lon lat
            lon lat
            ...
        END
        ...
        END

    For a single polygon, the first ring is the exterior and subsequent rings (if any)
    are interior rings (holes). For a MultiPolygon, each polygon's rings are written
    sequentially with unique ring identifiers.

    Parameters
    ----------
    gdf : GeoDataFrame
        A GeoDataFrame containing polygon (or multipolygon) geometries.
    out_filename : str, optional
        The output filename for the .poly file. Should be a full path to the file.

    Returns
    -------
    str
        The output filename of the generated .poly file.

    Raises
    ------
    ValueError
        If the unified geometry is not a polygon or multipolygon.
    """
    # Combine all geometries into a single geometry (union)
    if os.path.exists(out_filename):
        return out_filename

    union_geom = shapely.ops.unary_union(
        region_gdf.to_crs(
            "EPSG:4326",  #
            inplace=False,
        ).geometry
    )

    # Prepare a list of polygons
    if union_geom.geom_type == "Polygon":
        polygons = [union_geom]
    elif union_geom.geom_type == "MultiPolygon":
        polygons = list(union_geom)
    else:
        raise ValueError("GeoDataFrame does not contain polygonal geometries.")

    os.makedirs(
        name=os.path.dirname(out_filename),  #
        exist_ok=True,
    )

    if not out_filename.endswith(".poly"):
        out_filename += ".poly"

    # Get the name of the polygon
    polygon_name = os.path.splitext(os.path.basename(out_filename))[0]

    # Start building the file content as a list of lines.
    lines = [polygon_name]
    ring_counter = 1  # use a running counter to uniquely label each ring

    for poly in polygons:
        # Write the exterior ring first
        lines.append(f"{ring_counter}")
        ring_counter += 1
        for lon, lat in poly.exterior.coords:
            lines.append(f"    {lon} {lat}")
        lines.append("END")

        # Write any interior rings (holes)
        for interior in poly.interiors:
            lines.append(f"{ring_counter}")
            ring_counter += 1
            for lon, lat in interior.coords:
                lines.append(f"    {lon} {lat}")
            lines.append("END")

    # Final end line for the .poly file
    lines.append("END")

    # Write the lines to the specified output file
    with open(out_filename, "w") as f:
        f.write("\n".join(lines))

    os.chmod(out_filename, stat.S_IREAD | stat.S_IRGRP | stat.S_IROTH)

    return out_filename


def create_osm_region_road_network_extract_pbf(
    base_osm_pbf: os.PathLike,  #
    geoid: Optional[str],
    buffer_dist_mi: Optional[int] = DEFAULT_OSM_EXTRACT_BUFFER_DIST_MI,
    output_dir: Optional[os.PathLike] = DEFAULT_OSM_EXTRACTS_DIR,
    clean: bool = False,
    ways_filter: OSMWaysFilter = OSMWaysFilter.NONSERVICE,
) -> str:
    """Creates an OSM road network extract (PBF file) for a specified geographic region.

    This function leverages Osmosis to filter a base OpenStreetMap PBF file,
    producing a smaller PBF extract containing only road network data relevant
    to a specific geographic area. The area can be defined by a US Census GEOID
    and an optional buffer distance. A polygon filter file (`.poly`) is
    generated from the buffered region boundary to guide the Osmosis extraction.
    The extraction process is configured to include only specified highway types
    and ensures that all ways are complete by including necessary nodes.

    Args:
        base_osm_pbf (os.PathLike): The path to the input OpenStreetMap PBF file
            from which the extract will be created.
        geoid (Optional[str]): The US Census GEOID (e.g., '36001' for Albany County, NY)
            that defines the primary geographic region of interest. If None, no
            spatial filtering is applied.
        buffer_dist_mi (Optional[int]): An optional buffer distance in miles to
            extend around the `geoid` region. This ensures that roads just outside
            the strict boundary are also included. Defaults to
            `DEFAULT_OSM_EXTRACT_BUFFER_DIST_MI` (10 miles).
        output_dir (Optional[os.PathLike]): The directory where the generated
            `.poly` file and the output PBF extract will be saved. Defaults to
            `DEFAULT_OSM_EXTRACTS_DIR`.
        clean (bool): If `True`, forces the recreation of the output PBF file
            even if a file with the same name already exists. If `False` and the
            file exists, the existing file path is returned. Defaults to `False`.
        ways_filter (OSMWaysFilter): An enum member specifying which OSM ways to
            include based on highway tags. The filter determines both the
            Osmosis tag filtering arguments and the prefix for the output
            filename. Defaults to `OSMWaysFilter.NONSERVICE`.

    Returns:
        str: The absolute path to the newly created or existing OSM PBF extract file.

    Raises:
        subprocess.CalledProcessError: If the underlying Osmosis command fails
            during execution. Details of the error can be found in the associated
            log file generated alongside the output PBF.
    """
    filter_config = osmosis_tag_filters[ways_filter]
    osm_ways_filter_name = filter_config["name"]
    osm_tag_filter = filter_config["tag_filters"]

    if geoid:
        region_name = get_geography_region_name(
            geoid=geoid, buffer_dist_mi=buffer_dist_mi
        )

        region_prefix = f"{region_name}_"

        region_gdf = get_region_boundary_gdf(geoid)

        buffered_region_gdf = get_buffered_region_gdf(
            region_gdf=region_gdf,  #
            buffer_dist_mi=buffer_dist_mi,
        )

        poly_filename = os.path.join(output_dir, f"{region_name}.poly")

        output_osmosis_filter_poly(
            region_gdf=buffered_region_gdf,  #
            out_filename=poly_filename,
        )

        spatial_filter = [
            "--bounding-polygon",
            f"file={poly_filename}",
        ]
    else:
        region_prefix = ""  # No region, so no prefix
        spatial_filter = []

    output_file_basename = (
        f"{osm_ways_filter_name}-ways-{region_prefix}{os.path.basename(base_osm_pbf)}"
    )

    output_file = os.path.join(output_dir, output_file_basename)  # type: ignore

    if os.path.exists(output_file):
        if clean:
            os.remove(output_file)
        else:
            return output_file

    # https://github.com/openstreetmap/osmosis/blob/main/doc/detailed-usage.adoc
    osmium_extract_cmd = (
        [
            OSMOSIS,
            "--read-pbf-fast",
            base_osm_pbf,
        ]
        + spatial_filter
        + osm_tag_filter
        + [
            "completeWays=yes",
            "completeRelations=no",
            "--used-node",
            "--buffer",
            "500",
            "--sort",
            "type=TypeThenId",
            "--write-pbf",
            output_file,
        ]
    )

    log_filename = f"{output_file[: -len('.osm.pbf')]}.extract.log"

    with open(log_filename, "w") as log_file:
        try:
            subprocess.run(
                args=osmium_extract_cmd,  # The Osmosis command to run
                stdout=log_file,  # Pipe STDOUT to a log file
                stderr=log_file,  # Pipe STDERR to the same log file
                shell=False,  # Do not use shell to avoid shell injection vulnerabilities
                check=True,  # raise an error if the command fails
            )
        except subprocess.CalledProcessError as e:
            relative_path = os.path.relpath(OSMOSIS, os.getcwd())
            print(f"Error running Osmosis. Check the logfile: {log_filename}")
            print(f"Command: {'\n\t'.join([relative_path] + osmium_extract_cmd[1:])}")
            raise

    os.chmod(log_filename, stat.S_IREAD | stat.S_IRGRP | stat.S_IROTH)
    os.chmod(output_file, stat.S_IREAD | stat.S_IRGRP | stat.S_IROTH)

    return output_file
