services:
  rnr-analysis:
    image: avail-research-rnr:0.1.0
    container_name: rnr-analysis
    restart: "no"
    ports:
      - ${AVAIL_RNR_PYTHON_ANALYSIS_SSH_PORT}:22
    volumes:
      - ${PWD}/config/authorized_keys:/home/availien/.ssh/authorized_keys
      - ${PWD}/mount_dirs/shared_data:/shared_data
      # .venv is platform specific, so container needs its own.
      - ${PWD}/mount_dirs/rnr-analysis-venv:/home/availien/rnr-analysis/.venv
      - ${PWD}/mount_dirs/avail_research_road_network_resiliency/:/home/availien/rnr-analysis/avail_research_road_network_resiliency/
      - ${PWD}/mount_dirs/avail_research_road_network_resiliency.egg/:/home/availien/rnr-analysis/avail_research_road_network_resiliency.egg/
      - ${PWD}/../../:/home/availien/rnr-analysis/
    shm_size: 6g
  rnr-osrm:
    image: ${AVAIL_RNR_OSRM_DOCKER_VERSION}
    container_name: rnr-osrm
    restart: "no"
    ports:
      - ${AVAIL_RNR_OSRM_PORT}:5000
    volumes:
      - ${PWD}/../../data/processed/osrm/${AVAIL_RNR_OSRM_OSM_VERSION}:/data/
    entrypoint:
      - "osrm-routed"
      - "--max-matching-size"
      - "100000"
      - "/data/${AVAIL_RNR_OSRM_OSM_VERSION}.osrm"
    shm_size: 2g
